name: Compress and push to build branch

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: 'repo'
          fetch-depth: 0 # need to fetch all branches tips

      - name: Prepare the spoons
        working-directory: repo
        run: |
          npx zx <<'EOF'
          const dirs = await fs.readdir('Source');
          const spoons_paths = dirs.map(path.parse).filter(p => p.ext == '.spoon');

          const metadata = spoons_paths.map(p => ({name: p.name}));
          const docs_json = JSON.stringify(metadata, null, 2);

          await $`mkdir -p docs`;
          await fs.writeFile('docs/docs.json', docs_json);

          await $`rm -rf Spoons && mkdir -p Spoons`;
          cd ('Source');

          for await (const spoon of spoons_paths) {
            await $`zip -r ../Spoons/${spoon.base}.zip ${spoon.base}`;
          }
          EOF

      - name: Publish the spoons
        working-directory: repo
        run: |
          git config --global user.email "devnoname120@gmail.com"
          git config --global user.name "devnoname120"
          git stash --all
          git checkout build
          rm -r docs
          rm -r Spoons
          git status
          # git rm -r --cached .
          # git merge --squash --strategy-option=theirs stash --allow-unrelated-histories
          git stash pop
          git add -f docs
          git add -f Spoons/*.zip
          git status
          git commit --allow-empty -m "Build $GITHUB_SHA"
          git push origin build
