name: Compress and push to build branch

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: 'repo'
          fetch-depth: 0 # need to fetch all branches tips

      - name: Prepare the spoons
        working-directory: repo
        run: |
          spoons=$(find Source -type d -mindepth 1 -maxdepth 1 -exec basename {} \; | tr "\n" "\0" | sed -E 's/\.spoon//g')
          # Build the available spoons JSON
          mkdir -p docs
          echo -n "$spoons" | xargs -0 printf "  {\"name\": \"%s\"},\0" | rev | cut -c 2- | rev | tr "\0" "\n" | xargs -0 printf "[\n%s]\n" > docs/docs.json
          # Compress the spoons
          rm -rf Spoons && mkdir -p Spoons
          cd Source
          echo -n "$spoons" | xargs -0 -I SPOON_NAME zip -r ../Spoons/SPOON_NAME.spoon.zip SPOON_NAME.spoon
      
      - name: Publish the spoons
        working-directory: repo
        run: |
          git config --global user.email "devnoname120@gmail.com"
          git config --global user.name "devnoname120"
          git stash --all
          git checkout build
          git checkout stash -- . # Force restore files
          git rm -r --cached .
          git add -f docs
          git add -f Spoons/*.zip
          git commit --allow-empty -m "Build $GITHUB_SHA"
          git push origin build
